const
  vec2_Axis_PX: TVec2 = ( FCoord: ( 1.0, 0.0 ));
  vec2_Axis_PY: TVec2 = ( FCoord: ( 0.0, 1.0 ));
  vec2_Axis_NX: TVec2 = ( FCoord: ( -1.0, 0.0 ));
  vec2_Axis_NY: TVec2 = ( FCoord: ( 0.0, -1.0 ));

  vec3_Axis_PX: TVec3 = ( FCoord: ( 1.0, 0.0, 0.0 ));
  vec3_Axis_PY: TVec3 = ( FCoord: ( 0.0, 1.0, 0.0 ));
  vec3_Axis_PZ: TVec3 = ( FCoord: ( 0.0, 0.0, 1.0 ));
  vec3_Axis_NX: TVec3 = ( FCoord: ( -1.0, 0.0, 0.0 ));
  vec3_Axis_NY: TVec3 = ( FCoord: ( 0.0, -1.0, 0.0 ));
  vec3_Axis_NZ: TVec3 = ( FCoord: ( 0.0, 0.0, -1.0 ));

  Mat2Identity: TMat2 = ( m: ( 1.0, 0.0,
                               0.0, 1.0 ));
  Mat3Identity: TMat3 = ( m: ( 1.0, 0.0, 0.0,
                               0.0, 1.0, 0.0,
                               0.0, 0.0, 1.0 ));
  Mat4Identity: TMat4 = ( m: ( 1.0, 0.0, 0.0, 0.0,
                               0.0, 1.0, 0.0, 0.0,
                               0.0, 0.0, 1.0, 0.0,
                               0.0, 0.0, 0.0, 1.0 ));

