    { TIntList }  
  {$DEFINE TItem:= Integer}
  {$DEFINE TItemArray:= TIntArray}
  {$DEFINE TItemList:= TIntList}
  {$DEFINE pItemArray:= pIntArray}
  {$DEFINE TListEnumerator:= TIntListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= Float}
  {$DEFINE TItemArray:= TFloatArray}
  {$DEFINE TItemList:= TFloatList}
  {$DEFINE pItemArray:= pFloatArray}
  {$DEFINE TListEnumerator:= TFloatListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TVec2}
  {$DEFINE TItemArray:= TVec2Array}
  {$DEFINE TItemList:= TVec2List}
  {$DEFINE pItemArray:= pVec2Array}
  {$DEFINE TListEnumerator:= TVec2ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TVec3}
  {$DEFINE TItemArray:= TVec3Array}
  {$DEFINE TItemList:= TVec3List}
  {$DEFINE pItemArray:= pVec3Array}
  {$DEFINE TListEnumerator:= TVec3ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TVec4}
  {$DEFINE TItemArray:= TVec4Array}
  {$DEFINE TItemList:= TVec4List}
  {$DEFINE pItemArray:= pVec4Array}
  {$DEFINE TListEnumerator:= TVec4ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TMat2}
  {$DEFINE TItemArray:= TMat2Array}
  {$DEFINE TItemList:= TMat2List}
  {$DEFINE pItemArray:= pMat2Array}
  {$DEFINE TListEnumerator:= TMat2ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TMat3}
  {$DEFINE TItemArray:= TMat3Array}
  {$DEFINE TItemList:= TMat3List}
  {$DEFINE pItemArray:= pMat3Array}
  {$DEFINE TListEnumerator:= TMat3ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}

  {$DEFINE TItem:= TMat4}
  {$DEFINE TItemArray:= TMat4Array}
  {$DEFINE TItemList:= TMat4List}
  {$DEFINE pItemArray:= pMat4Array}
  {$DEFINE TListEnumerator:= TMat4ListEnumerator}
  {$INCLUDE p3dmath_arrays.inc}
