{$IFDEF INTERFACE}
TIVec2 = array[ 0..2 ] of Integer;
TIVec2Array = array [ 0..( MAXINT shr 8 )] of TIVec2;
TIVec3 = array[ 0..3 ] of Integer;
TIVec3Array = array [ 0..( MAXINT shr 8 )] of TIVec3;
TIVec4 = array[ 0..4 ] of Integer;
TIVec4Array = array [ 0..( MAXINT shr 8 )] of TIVec4;

TBVec2 = array[ 0..2 ] of Boolean;
TBVec2Array = array [ 0..( MAXINT shr 8 )] of TBVec2;
TBVec3 = array[ 0..3 ] of Boolean;
TBVec3Array = array [ 0..( MAXINT shr 8 )] of TBVec3;
TBVec4 = array[ 0..4 ] of Boolean;
TBVec4Array = array [ 0..( MAXINT shr 8 )] of TBVec4;
{$ENDIF}

{$IFDEF IMPLEMENTATION}
{$ENDIF}
