{ p3d.ideintf_lib.inc }

{$INCLUDE p3d.ide_propertyeditor.inc}
{$INCLUDE p3d.ide_toolbar.inc}
{$INCLUDE p3d.ide_editorlibrary.inc}
{$INCLUDE p3d.ide_editorscene.inc}
{$INCLUDE p3d.ide_editormaterial.inc}
{$INCLUDE p3d.ide_editortexture.inc}
{$INCLUDE p3d.ide_editormesh.inc}
{$INCLUDE p3d.ide_editoreffect.inc}
{$INCLUDE p3d.ide_libinspector.inc}
{$INCLUDE p3d.ide_objectinspector.inc}
{$INCLUDE p3d.ide_objectinspector_editors.inc}
{$INCLUDE p3d.ide_sceneviewer.inc}
{$INCLUDE p3d.ide_shadernodes_controls.inc}
{$INCLUDE p3d.ide_shadernodes.inc}

